name: Run Auto Pushy v2

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      SCRIPT_CONTENT: ${{ vars.SCRIPT_CONTENT }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create Python Script
      run: |
        cat <<EOF > script.py
        ${{ env.SCRIPT_CONTENT }}
        EOF

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Change this to your Python version if needed

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python Script
      run: python script.py
      
    - name: List Files in Current Directory
      run: ls $GITHUB_WORKSPACE

    - name: List Files
      run: ls

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        # Optional. Commit message for the created commit.
        # Defaults to "Apply automatic changes"
        commit_message: Automated Change
        repository: .
        file_pattern: '*.json'
