name: Run Auto Pushy v2

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      SCRIPT_CONTENT: ${{ secrets.SCRIPT_CONTENT }}

    steps:
    - name: Create Python Script
      run: printf "%s" "${{ secrets.SCRIPT_CONTENT }}" > script.py

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Change this to your Python version if needed

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python Script
      run: python script.py

    - name: Commit Changes
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git add output.json  # Assuming your generated file is named output.json
        git commit -m "Update generated file"
        git push
