name: JavaScript Runner

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Run JavaScript
      env:
        SCRIPT_CONTENT: ${{ secrets.myJS }}
      run: echo "$SCRIPT_CONTENT" > your-script.js && node your-script.js
