name: JavaScript Runner

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Run JavaScript
      env:
        SCRIPT_CONTENT: ${{ secrets.myJS }}
      run: |
        echo "$SCRIPT_CONTENT" > your-script.js
        node your-script.js

    - name: Add, Commit and Push Output
      uses: stefanzweifel/git-auto-commit-action@v3
      with:
        commit_message: "Auto-commit by Github Actions"
        file: "output.json"
        github_token: ${{ secrets.GITHUB_TOKEN }}
